///////////////////////////////////////////////////////////
//  Controler.cs
//  Implementation of the Class Controler
//  Generated by Enterprise Architect
//  Created on:      25-февр.-2026 12:17:25
//  Original author: v.belov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SolidWorks.Interop.sldworks;

namespace StructuralWeldment
{
	public class Controler {

        private Service service;
        private Weldment wd;
        public Controler(SldWorks sw){
            service = new Service(sw);
            wd = service.GetWeldment();
            double[] box = service.GetPointsBoundinBox();

            double[][] Points = wd.GetCentetPonts(box);
            
            string nameAxis = service.AddAxis(Points);
            string namePlaneBase = service.AddPlaneWork(nameAxis, wd.namePlane, (int)wd.rotationAxis);

            double[] PontsFirst = wd.GetPointsFirstExtrude(true);
            service.AddSketch(namePlaneBase, PontsFirst);

            double[] PontsSecond = wd.GetPointsSecondExtrude(PontsFirst);
            service.AddSketch(namePlaneBase, PontsSecond);
        }


		public void Completion(){

		}

		public void Reverse(){

		}

		public void Rotate(){

		}

	}

}

