///////////////////////////////////////////////////////////
//  Controler.cs
//  Implementation of the Class Controler
//  Generated by Enterprise Architect
//  Created on:      25-февр.-2026 12:17:25
//  Original author: v.belov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;
using System.Windows.Forms;

namespace StructuralWeldment
{
	public class Controler {

        private Service service;
        private Weldment wd;
        public static clsPropMgr pm;
       

        public Controler(SldWorks sw)
        {

            service = new Service(sw);
            wd = service.GetWeldment();
            sw.SetUserPreferenceToggle((int)swUserPreferenceToggle_e.swStopDebuggingVstaOnExit, false);
            pm = new clsPropMgr(sw);        
            pm.PreviewRequested += OnPreviewRequested;
            pm.ApplyRequested += OnApplyRequested;
            pm.Show();
            if (pm != null)
            {
                while (pm.IsOpen)
                {
                    Application.DoEvents();
                }

            }


        }

        private void OnApplyRequested(object sender, ApplyEventArgs e)
        {
            wd.axis = e.Angle * 180.0 / Math.PI;
            wd.rotationAxis = (RotationAxis)e.Rotation;

            service.BuildCutBody(wd);
        }

        private void OnPreviewRequested(object sender, PreviewEventArgs e)
        {
            wd.axis = e.Angle * 180.0 / Math.PI;
            wd.rotationAxis = (RotationAxis)e.Rotation;

            service.PreviewCutBody(wd);
        }


	}

}

