///////////////////////////////////////////////////////////
//  PmpPage.cs
//  Implementation of the Class PmpPage
//  Generated by Enterprise Architect
//  Created on:      26-февр.-2026 12:32:30
//  Original author: v.belov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using ExternalLayer.SolidWorks.Interop.sldworks;
namespace StructuralWeldment {
	public class PmpPage {

		private int Angle;
		private bool Direction;

		public PmpPage(){

		}

		~PmpPage(){

		}

		/// 
		/// <param name="swSldWorks"></param>
		public PmpPage(SldWorks swSldWorks){

		}

	}//end PmpPage

}//end namespace StructuralWeldment