///////////////////////////////////////////////////////////
//  Service.cs
//  Implementation of the Class Service
//  Generated by Enterprise Architect
//  Created on:      20-февр.-2026 11:52:48
//  Original author: v.belov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;

namespace StructuralWeldment
{
	public class Service {

		private FeatureManager fm;
		private MathUtility mathUtility;
		private SelectionMgr slMg;
		public  SldWorks swApp;
		private ModelDoc2 model;
        private PartDoc part;
        private SelectionMgr selMgr;
        private ModelDocExtension swModelDocExt;
        SketchManager swSkMgr = default(SketchManager);
        bool statusSelect;

        public Service(SldWorks swSld){
             swApp = swSld;
             model = (ModelDoc2)swApp.ActiveDoc;
             CheckingIsPart();
             part = (PartDoc)model;
             mathUtility = (MathUtility)swApp.GetMathUtility();
             swModelDocExt = model.Extension;
             fm = model.FeatureManager;
             selMgr = (SelectionMgr)model.SelectionManager;
             swSkMgr = model.SketchManager;
        }


        public string AddAxis(double[][] Points){

            double[] A = Points[0];
            double[] B = Points[1];

            swSkMgr.Insert3DSketch(true);  
            SketchSegment swSketchSegment = swSkMgr.CreateLine(A[0], A[1], A[2], B[0], B[1], B[2]);
            swSketchSegment.ConstructionGeometry = true;

            swSkMgr.Insert3DSketch(false);
            model.ClearSelection2(true);
            swSketchSegment.Select(true);
            statusSelect = model.InsertAxis2(true);
           
            Feature featAxis = (Feature)selMgr.GetSelectedObject6(1, 0);
            if (featAxis == null)
            {
                swApp.SendMsgToUser("Не удалось создать ось по сегменту.");
            }


            RefAxis axis = featAxis.GetSpecificFeature2() as RefAxis;
            if (axis == null)
            {
                // Иногда нужно получать через Feature.GetDefinition() -> RefAxis; но оставим проверку
                // TODO: при ошибке — заменить на ((RefAxis)featAxis.GetDefinition())
            }
            string nameAxis = featAxis.Name;
            return nameAxis;
                 
        }


		public string AddPlaneWork(string nameAxis, string namePlaneSketch, int angle)
        {
            model.ClearSelection2(true);
            // выделяем axis и plane по имени (SelectByID2)
            statusSelect = swModelDocExt.SelectByID2(nameAxis, "AXIS", 0, 0, 0, false, 0, null, (int)swSelectOption_e.swSelectOptionDefault);
            statusSelect = swModelDocExt.SelectByID2(namePlaneSketch, "PLANE", 0, 0, 0, true, 1, null, (int)swSelectOption_e.swSelectOptionDefault);

            // создаём плоскость: Coincident (ось) и Angle (плоскость эскиза) — угол используем из group.Angle
            RefPlane newPlane = (RefPlane)fm.InsertRefPlane(
                (int)swRefPlaneReferenceConstraints_e.swRefPlaneReferenceConstraint_Coincident, 0,
                (int)swRefPlaneReferenceConstraints_e.swRefPlaneReferenceConstraint_Angle, angle,
                0, 0);

            if (newPlane == null)
            {
                swApp.SendMsgToUser("Ошибка: не удалось создать опорную плоскость.");
                return null;
            }
            Feature PlaneWorkPlane = (Feature)newPlane;
            string plane = PlaneWorkPlane.Name;
            return plane;
		}


		public void AddSketch(string planeWorkName, double[] points){
            model.ClearSelection2(true);
 
            statusSelect = swModelDocExt.SelectByID2(planeWorkName, "PLANE", 0, 0, 0, true, 1, null, (int)swSelectOption_e.swSelectOptionDefault);
            swSkMgr.InsertSketch(true);
            CreateClosedSketch(points);
            Sketch sketchPlane1 = (Sketch)swSkMgr.ActiveSketch as Sketch;
            Feature sketchFeatureName = (Feature)sketchPlane1;
            string nameSketch = sketchFeatureName.Name;
            FullyDefineSketch(nameSketch);
            swSkMgr.InsertSketch(false);
            Extrude();
            return;
		}

        private void FullyDefineSketch(string name)
        {
            model.ClearSelection2(true);

            swModelDocExt.SelectByID2(
                name,
                "SKETCH",
                0, 0, 0,
                false, 0, null, 0);

            model.SketchAddConstraints("sgFIXED");
        }


        private  void CreateClosedSketch(double[] pts)
        {
            int count = pts.Length / 3;

            if (count < 3)
                throw new Exception("Нужно минимум 3 точки");

            swSkMgr.CreateLine(
                 pts[0], pts[1], pts[2],
                 pts[6], pts[7], pts[8]);

            swSkMgr.CreateLine(
                pts[3], pts[4], pts[5],
                pts[6], pts[7], pts[8]);

            swSkMgr.CreateLine(
                pts[0], pts[1], pts[2],
                pts[3], pts[4], pts[5]);
        }
        
        public void Extrude(){


            Feature extrude = ((Feature)(model.FeatureManager.FeatureCut4(false, false, false, 9, 1,
                0.0, 0.0, false, false, false, false,
                0.0, 0.0, false, false, false, false,
                false, true, true, true, true, false, 0, 0, false, false)));
        
    }

		/* public Weldment GetParamWeldment(){
            Feature swFeat = (Feature)model.FirstFeature();
            StructuralMemberFeatureData weldData = null;
            while (swFeat != null)
            {
                string tmp = swFeat.GetTypeName();
                if (swFeat.GetTypeName() == "WeldMemberFeat")
                {
                    weldData = (StructuralMemberFeatureData)swFeat.GetDefinition();
                    break;
                }
                else
                {
                    swFeat = (Feature)swFeat.GetNextFeature();
                }
            }

            if (weldData == null)
            {
                swApp.SendMsgToUser("No Structural Member (элемент сварной балки).");
                return null;
            }

            // Получаем группы и сегменты и проверяем что ровно одна группа и ровно один сегмент
            weldData.AccessSelections(model, null);
            object[] groups = (object[])weldData.Groups;

            if (groups == null || groups.Length != 1)
            {
                swApp.SendMsgToUser("Элемент должен содержать ровно одну группу.");
                weldData.ReleaseSelectionAccess();
                return null;
            }

            StructuralMemberGroup group = (StructuralMemberGroup)groups[0];
            object[] segs = (object[])group.Segments;

            if (segs == null || segs.Length != 1)
            {
                swApp.SendMsgToUser("В группе должен быть ровно один сегмент.");
                weldData.ReleaseSelectionAccess();
                return null;
            }


            // Получаем сегмент и линию
            SketchSegment seg = (SketchSegment)segs[0];
            SketchLine line = seg as SketchLine;
            if (line == null)
            {
                swApp.SendMsgToUser("Сегмент должен быть линией.");
                weldData.ReleaseSelectionAccess();
                return null;
            }
            // --- 3) Получаем плоскость эскиза, на которой лежит исходный сегмент ---
            Sketch sketch = (Sketch)seg.GetSketch();
            if (sketch == null)
            {
                swApp.SendMsgToUser("Не удалось получить эскиз сегмента.");
                return null;
            }
            return null;
		}
        */

        public Weldment GetWeldment()
        {
            Feature swFeat = (Feature)model.FirstFeature();
            StructuralMemberFeatureData weldData = null;
            while (swFeat != null)
            {
                string tmp = swFeat.GetTypeName();
                if (swFeat.GetTypeName() == "WeldMemberFeat")
                {

                    weldData = (StructuralMemberFeatureData)swFeat.GetDefinition();
                    break;
                }
                else
                {
                    swFeat = (Feature)swFeat.GetNextFeature();
                }

            }

            if (weldData == null)
            {
                swApp.SendMsgToUser("No Structural Member (элемент сварной балки).");
                return null;
            }

          
            // Получаем группы и сегменты и проверяем что ровно одна группа и ровно один сегмент
            weldData.AccessSelections(model, null);
            object[] groups = (object[])weldData.Groups;

            if (groups == null || groups.Length != 1)
            {
                swApp.SendMsgToUser("Элемент должен содержать ровно одну группу.");
                weldData.ReleaseSelectionAccess();
                return null;
            }

            StructuralMemberGroup group = (StructuralMemberGroup)groups[0];
            object[] segs = (object[])group.Segments;

            if (segs == null || segs.Length != 1)
            {
                swApp.SendMsgToUser("В группе должен быть ровно один сегмент.");
                weldData.ReleaseSelectionAccess();
                return null;
            }


            // Получаем сегмент и линию
            SketchSegment seg = (SketchSegment)segs[0];
            SketchLine line = seg as SketchLine;
            if (line == null)
            {
                swApp.SendMsgToUser("Сегмент должен быть линией.");
                weldData.ReleaseSelectionAccess();
                return null;
            }
            // --- 3) Получаем плоскость эскиза, на которой лежит исходный сегмент ---
            Sketch sketch = (Sketch)seg.GetSketch();
            if (sketch == null)
            {
                swApp.SendMsgToUser("Не удалось получить эскиз сегмента.");
                return null;
            }
            int nEntType=0;
            Feature pPlaneFeat = null;
            Entity pEntity =(Entity)sketch.GetReferenceEntity(ref nEntType);
            if (nEntType == (int)swSelectType_e.swSelDATUMPLANES) {
                pPlaneFeat = (Feature)pEntity;
            }

            string namePlane = pPlaneFeat.Name;

            // Получаем начало и конец линии (координаты в модели)
            ISketchPoint point1 = (ISketchPoint)line.GetStartPoint2(); // {x,y,z}
            ISketchPoint point2 = (ISketchPoint)line.GetEndPoint2();
            double[] p1 = new double[3];
            double[] p2 = new double[3];
            p1[0] = point1.X;
            p1[1] = point1.Y;
            p1[2] = point1.Z;
            p2[0] = point2.X;
            p2[1] = point2.Y;
            p2[2] = point2.Z;        //To global ..............
            // Сохраняем угол (если понадобится)
            double angle = group.Angle;
            weldData.ReleaseSelectionAccess();
            string templatePath = weldData.WeldmentProfilePath;
            string template = Path.GetFileNameWithoutExtension(templatePath);
            string[] parametry = template.Split('x');
            Weldment profile = new Weldment(template);
            profile.SetCenterPoits(p1, p2);
            profile.namePlane = namePlane;
            return profile;
        }

        public double[] GetPointsBoundinBox(){
            
 
            double[] box = null;

            try
            {
                box = part.GetPartBox(true) as double[];
            }
            catch
            {
                swApp.SendMsgToUser("Не удалось получить bounding box детали. Проверьте версию API.");
                return null;
            }


            if (box == null || box.Length < 6)
            {
                swApp.SendMsgToUser("Не удалось получить корректный bounding box.");
                return null;
            }

            return box;
        }

		public void Reverse(){

		}

		public void Rotate(){

		}

        private void CheckingIsPart()
        {
            if (model == null || model.GetType() != (int)swDocumentTypes_e.swDocPART)
            {
                swApp.SendMsgToUser("Откройте деталь (Part) и запустите макрос.");
                return;
            }
        }

    }

}

