///////////////////////////////////////////////////////////
//  Service.cs
//  Implementation of the Class Service
//  Generated by Enterprise Architect
//  Created on:      20-февр.-2026 11:52:48
//  Original author: v.belov
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SolidWorks.Interop.sldworks;
using SolidWorks.Interop.swconst;
using System.Windows.Forms;
using System.Linq;

namespace StructuralWeldment
{
	public class Service {

		private FeatureManager fm;
		private MathUtility mathUtility;
		private SelectionMgr slMg;
		public  SldWorks swApp;
		private ModelDoc2 model;
        private PartDoc part;
        private SelectionMgr selMgr;
        private ModelDocExtension swModelDocExt;
        SketchManager swSkMgr = default(SketchManager);
        bool statusSelect;

        public Service(SldWorks swSld){
             swApp = swSld;
             model = (ModelDoc2)swApp.ActiveDoc;
             if (model == null || model.GetType() != (int)swDocumentTypes_e.swDocPART)
             {
                swApp.SendMsgToUser("Откройте деталь перед запуском макроса.");
                return;
             }
             CheckingIsPart();
             part = (PartDoc)model;
             mathUtility = (MathUtility)swApp.GetMathUtility();
             swModelDocExt = model.Extension;
             fm = model.FeatureManager;
             selMgr = (SelectionMgr)model.SelectionManager;
             swSkMgr = model.SketchManager;
        }

        public Body2 BuildCutBody(Weldment wd)
        {
            model.ClearSelection2(true);

            // --- базовая геометрия ---
            double[] box = GetPointsBoundinBox();
            double[][] axisPts = wd.GetCentetPonts(box);

            string axis = AddAxis(axisPts);
            string plane = AddPlaneWork(axis, wd.namePlane, (int)wd.rotationAxis);

            // --- первый профиль ---
            double[] p1 = wd.GetPointsFirstExtrude(true);
            string sk1 = CreateSketch(plane, p1);

            // --- второй профиль ---
            double[] p2 = wd.GetPointsSecondExtrude(p1);
            string sk2 = CreateSketch(plane, p2);

            // --- создаём tool body ---
            Body2 toolBody = CreateToolBody(new[] { sk1 });

            if (toolBody == null)
                throw new Exception("Не удалось создать tool body");
            ApplyCut(wd);

            return toolBody;
        }

        public bool ApplyCut(Weldment wd)
        {
            if (wd == null)
            {
                swApp.SendMsgToUser("Weldment = null");
                return false;
            }

            Body2 toolBody = BuildCutBody(wd);
            Body2 baseBody = GetMainBody();

            if (toolBody == null || baseBody == null)
            {
                swApp.SendMsgToUser("Ошибка: нет тел для операции");
                return false;
            }

            model.ClearSelection2(true);

            // ВАЖНО: сначала base, потом tool
            bool sel1 = baseBody.Select2(false, null);
            bool sel2 = toolBody.Select2(true, null);

            if (!sel1 || !sel2)
            {
                swApp.SendMsgToUser("Ошибка выбора тел");
                return false;
            }

            Feature cut = fm.InsertCombineFeature(
                (int)swBodyOperationType_e.SWBODYCUT,
                null,
                null
            );
            DeleteBody(toolBody);

            if (cut == null)
            {
                swApp.SendMsgToUser("Ошибка: Combine Cut не выполнен");
                return false;
            }

            model.ClearSelection2(true);

            return true;
        }

        private void DeleteBody(Body2 body)
        {
            if (body == null) return;

            model.ClearSelection2(true);

            body.Select2(false, null);

            model.Extension.DeleteSelection2(
                (int)swDeleteSelectionOptions_e.swDelete_Absorbed);
        }


        public string AddAxis(double[][] Points){

            double[] A = Points[0];
            double[] B = Points[1];

            swSkMgr.Insert3DSketch(true);  
            SketchSegment swSketchSegment = swSkMgr.CreateLine(A[0], A[1], A[2], B[0], B[1], B[2]);
            swSketchSegment.ConstructionGeometry = true;

            swSkMgr.Insert3DSketch(false);
            model.ClearSelection2(true);
            swSketchSegment.Select(true);
            statusSelect = model.InsertAxis2(true);
           
            Feature featAxis = (Feature)selMgr.GetSelectedObject6(1, 0);
            if (featAxis == null)
            {
                swApp.SendMsgToUser("Не удалось создать ось по сегменту.");
            }


            RefAxis axis = featAxis.GetSpecificFeature2() as RefAxis;
            if (axis == null)
            {
                // Иногда нужно получать через Feature.GetDefinition() -> RefAxis; но оставим проверку
                // TODO: при ошибке — заменить на ((RefAxis)featAxis.GetDefinition())
            }
            string nameAxis = featAxis.Name;
            return nameAxis;
                 
        }


		public string AddPlaneWork(string nameAxis, string namePlaneSketch, int angle)
        {
            model.ClearSelection2(true);
            // выделяем axis и plane по имени (SelectByID2)
            statusSelect = swModelDocExt.SelectByID2(nameAxis, "AXIS", 0, 0, 0, false, 0, null, (int)swSelectOption_e.swSelectOptionDefault);
            statusSelect = swModelDocExt.SelectByID2(namePlaneSketch, "PLANE", 0, 0, 0, true, 1, null, (int)swSelectOption_e.swSelectOptionDefault);

            // создаём плоскость: Coincident (ось) и Angle (плоскость эскиза) — угол используем из group.Angle
            RefPlane newPlane = (RefPlane)fm.InsertRefPlane(
                (int)swRefPlaneReferenceConstraints_e.swRefPlaneReferenceConstraint_Coincident, 0,
                (int)swRefPlaneReferenceConstraints_e.swRefPlaneReferenceConstraint_Angle, angle,
                0, 0);

            if (newPlane == null)
            {
                swApp.SendMsgToUser("Ошибка: не удалось создать опорную плоскость.");
                return null;
            }
            Feature PlaneWorkPlane = (Feature)newPlane;
            string plane = PlaneWorkPlane.Name;
            return plane;
		}


		public void AddSketch(string planeWorkName, double[] points){
            model.ClearSelection2(true);
 
            statusSelect = swModelDocExt.SelectByID2(planeWorkName, "PLANE", 0, 0, 0, true, 1, null, (int)swSelectOption_e.swSelectOptionDefault);
            swSkMgr.InsertSketch(true);
            CreateClosedSketch(points);
            Sketch sketchPlane1 = (Sketch)swSkMgr.ActiveSketch as Sketch;
            Feature sketchFeatureName = (Feature)sketchPlane1;
            string nameSketch = sketchFeatureName.Name;
            FullyDefineSketch(nameSketch);
            swSkMgr.InsertSketch(false);
            Extrude();
            return;
		}

        public string CreateSketch(string plane, double[] pts)
        {
            model.ClearSelection2(true);

            swModelDocExt.SelectByID2(plane, "PLANE", 0, 0, 0, false, 0, null, 0);

            swSkMgr.InsertSketch(true);

            CreateClosedSketch(pts);

            Sketch sk = (Sketch)swSkMgr.ActiveSketch;
            Feature feat = (Feature)sk;

            string name = feat.Name;

            swSkMgr.InsertSketch(false);

            return name;
        }

        private void FullyDefineSketch(string name)
        {
            model.ClearSelection2(true);

            swModelDocExt.SelectByID2(
                name,
                "SKETCH",
                0, 0, 0,
                false, 0, null, 0);

            model.SketchAddConstraints("sgFIXED");
        }


        private  void CreateClosedSketch(double[] pts)
        {
            int count = pts.Length / 3;

            if (count < 3)
                throw new Exception("Нужно минимум 3 точки");

            swSkMgr.CreateLine(
                 pts[0], pts[1], pts[2],
                 pts[6], pts[7], pts[8]);

            swSkMgr.CreateLine(
                pts[3], pts[4], pts[5],
                pts[6], pts[7], pts[8]);

            swSkMgr.CreateLine(
                pts[0], pts[1], pts[2],
                pts[3], pts[4], pts[5]);
        }
        
        public void Extrude(){


            Feature extrude = ((Feature)(model.FeatureManager.FeatureCut4(false, false, false, 9, 1,
                0.0, 0.0, false, false, false, false,
                0.0, 0.0, false, false, false, false,
                false, true, true, true, true, false, 0, 0, false, false)));
        
    }

        private Body2 CreateToolBody(string[] sketches)
        {
            model.ClearSelection2(true);

            foreach (var sk in sketches)
            {
                swModelDocExt.SelectByID2(sk, "SKETCH", 0, 0, 0, true, 0, null, 0);

/*
                 Feature feat = fm.FeatureCut4
                               (false,
                                false,
                                false,
                                0,
                                0,
                                0.01000000000000000021,
                                0.01000000000000000021,
                                false,
                                false,
                                false,
                                false,
                                0.01745329251994333364,
                                0.01745329251994333364,
                                false,
                                false,
                                false,
                                false,
                                false,
                                true,
                                true,
                                true,
                                true,
                                false,
                                0,
                                0,
                                false,
                                false); 
 */
              Feature feat = fm.FeatureExtrusion3(
               false,   // solid
               false,   //Flip
               false,   //Dir
               (int)swEndConditions_e.swEndCondBlind,
               (int)swEndConditions_e.swEndCondBlind,
               0.01, 0.01,
               false,  //Dchk1
               false,  ////Dchk2
               false,
               false,
               0.0,
               0.0,
               false,     //OffsetReverse1            
               false,     //OffsetReverse2
               false,     //TranslateSurface1
               false,      //TranslateSurface2  
               false,      //Merge 
               true,      //UseFeatScope
               true,      //UseAutoSelect 
               0,        //T0
               0.0,      //StartOffset
               false);   //FlipStartOffset 
                if (feat == null)
                    throw new Exception("Extrude не создан");
            }
             object[] bodies = (object[])part.GetBodies2((int)swBodyType_e.swSolidBody,true);
          
             if (bodies == null || bodies.Length == 0)
                 throw new Exception("Tool body не найден");

            return bodies[1] as Body2;
        }
        private Body2 previewBody;

        public void UpdatePreview()
        {
            object[] bodies = (object[])part.GetBodies2((int)swBodyType_e.swSolidBody, true);
            Body2 baseBody = bodies[0] as Body2;
            Body2 toolBody = bodies[1] as Body2;
            if (baseBody == null || toolBody == null)
                return;

            if (previewBody != null)
                previewBody.HideBody(true);

            previewBody = (Body2)baseBody.Copy();
            string n11 = baseBody.Name;
            string n1 = previewBody.Name;
            string n2 = toolBody.Name;
            // baseBody.HideBody(true);



            FaultEntity check1 = (FaultEntity)previewBody.Check3;
            FaultEntity check2 = toolBody.Check3;
            int e1 = check1.ErrorCode[0];
            int e2 = check2.ErrorCode[0];
            // if (check1 != 0 || check2 != 0)
            //    throw new Exception("Invalid body geometry");

            int err;
         
            previewBody.Operations2(
                (int)swBodyOperationType_e.SWBODYCUT,
                toolBody,
                out err
            );

            if (err != 0)
                throw new Exception("Boolean failed: " + err);
          /*
            double[] color = new double[9];

            // RGB (0..1)
            color[0] = 1.0; // R
            color[1] = 0.0; // G
            color[2] = 0.0; // B

            // Ambient / Diffuse / Specular / Shininess / Transparency / Emission
            color[3] = 1.0; // Ambient
            color[4] = 1.0; // Diffuse
            color[5] = 1.0; // Specular
            color[6] = 0.5; // Shininess (0..1)
            color[7] = 0.0; // Transparency (0 = непрозрачный)
            color[8] = 0.0; // Emission

            previewBody.MaterialPropertyValues2 = color;
            */
            int u= previewBody.Display3(model,
                255,
                (int)swTempBodySelectOptions_e.swTempBodySelectable
                );
            string o = u.ToString();
        }

        public bool PreviewCutBody(Weldment wd)
        {
            //Body2 baseBody = GetMainBody();

            double[] box = GetPointsBoundinBox();
            double[][] axisPts = wd.GetCentetPonts(box);

            string axis = AddAxis(axisPts);
            string plane = AddPlaneWork(axis, wd.namePlane, (int)wd.rotationAxis);

            double[] p1 = wd.GetPointsFirstExtrude(true);
            string sk1 = CreateSketch(plane, p1);

           // double[] p2 = wd.GetPointsSecondExtrude(p1);
           // string sk2 = CreateSketch(plane, p2);

            Body2 toolBody = CreateToolBody(new[] { sk1 });
            model.EditRebuild3();
         
            /*
           bool st =swModelDocExt.SelectByID2(baseBody.Name, "SOLIDBODY", 0,0,0,false,1,null,0);
            st= swModelDocExt.SelectByID2(toolBody.Name, "SOLIDBODY", 0, 0, 0, true, 2, null, 0);
            Feature cut = fm.InsertCombineFeature(
                (int)swBodyOperationType_e.SWBODYCUT,
                null, null
            );
            */
                        
           UpdatePreview();

            return true;
        }

        public Body2 GetMainBody()
        {
            PartDoc part = (PartDoc)model;
            object[] bodies = (object[])part.GetBodies2((int)swBodyType_e.swSolidBody, true);

            if (bodies == null || bodies.Length == 0)
                throw new Exception("Нет базового тела");

            return bodies[0] as Body2;
        }

        public Weldment GetWeldment()
        {
            Feature swFeat = (Feature)model.FirstFeature();
            StructuralMemberFeatureData weldData = null;
            while (swFeat != null)
            {
                string tmp = swFeat.GetTypeName();
                if (swFeat.GetTypeName() == "WeldMemberFeat")
                {

                    weldData = (StructuralMemberFeatureData)swFeat.GetDefinition();
                    break;
                }
                else
                {
                    swFeat = (Feature)swFeat.GetNextFeature();
                }

            }

            if (weldData == null)
            {
                swApp.SendMsgToUser("No Structural Member (элемент сварной балки).");
                return null;
            }

          
            // Получаем группы и сегменты и проверяем что ровно одна группа и ровно один сегмент
            weldData.AccessSelections(model, null);
            object[] groups = (object[])weldData.Groups;

            if (groups == null || groups.Length != 1)
            {
                swApp.SendMsgToUser("Элемент должен содержать ровно одну группу.");
                weldData.ReleaseSelectionAccess();
                return null;
            }

            StructuralMemberGroup group = (StructuralMemberGroup)groups[0];
            object[] segs = (object[])group.Segments;

            if (segs == null || segs.Length != 1)
            {
                swApp.SendMsgToUser("В группе должен быть ровно один сегмент.");
                weldData.ReleaseSelectionAccess();
                return null;
            }


            // Получаем сегмент и линию
            SketchSegment seg = (SketchSegment)segs[0];
            SketchLine line = seg as SketchLine;
            if (line == null)
            {
                swApp.SendMsgToUser("Сегмент должен быть линией.");
                weldData.ReleaseSelectionAccess();
                return null;
            }
            // --- 3) Получаем плоскость эскиза, на которой лежит исходный сегмент ---
            Sketch sketch = (Sketch)seg.GetSketch();
            if (sketch == null)
            {
                swApp.SendMsgToUser("Не удалось получить эскиз сегмента.");
                return null;
            }
            int nEntType=0;
            Feature pPlaneFeat = null;
            Entity pEntity =(Entity)sketch.GetReferenceEntity(ref nEntType);
            if (nEntType == (int)swSelectType_e.swSelDATUMPLANES) {
                pPlaneFeat = (Feature)pEntity;
            }

            string namePlane = pPlaneFeat.Name;

            // Получаем начало и конец линии (координаты в модели)
            ISketchPoint point1 = (ISketchPoint)line.GetStartPoint2(); // {x,y,z}
            ISketchPoint point2 = (ISketchPoint)line.GetEndPoint2();
            double[] p1 = new double[3];
            double[] p2 = new double[3];
            p1[0] = point1.X;
            p1[1] = point1.Y;
            p1[2] = point1.Z;
            p2[0] = point2.X;
            p2[1] = point2.Y;
            p2[2] = point2.Z;        //To global ..............
            // Сохраняем угол (если понадобится)
            double angle = group.Angle;
            weldData.ReleaseSelectionAccess();
            string templatePath = weldData.WeldmentProfilePath;
            string template = Path.GetFileNameWithoutExtension(templatePath);
            string[] parametry = template.Split('x');
            Weldment profile = new Weldment(template);
            profile.SetCenterPoits(p1, p2);
            profile.namePlane = namePlane;
            return profile;
        }

        public double[] GetPointsBoundinBox(){
            
 
            double[] box = null;

            try
            {
                box = part.GetPartBox(true) as double[];
            }
            catch
            {
                swApp.SendMsgToUser("Не удалось получить bounding box детали. Проверьте версию API.");
                return null;
            }


            if (box == null || box.Length < 6)
            {
                swApp.SendMsgToUser("Не удалось получить корректный bounding box.");
                return null;
            }

            return box;
        }

		public void Reverse(){

		}

		public void Rotate(){

		}

        private void CheckingIsPart()
        {
            if (model == null || model.GetType() != (int)swDocumentTypes_e.swDocPART)
            {
                swApp.SendMsgToUser("Откройте деталь (Part) и запустите макрос.");
                return;
            }
        }

    }

}

